### ISSUE TITLE
Team Sunbeams 111 -ror-social-scaffold

### ISSUE THREAD

**Issue by temesghentekeste** [microverseinc/ror-social-scaffold#189]
The team's feedback:
-  The presentation was clear, refreshing, and easy to follow.
-  The whole project is still a work in progress.

Things to improve: 
-  The link in the Like model either should be changed between Like and Comment or the foreign key in the Like model should be changed to post_id to reflect the relationship between Post and Like.
-  The ERD needs some small modification to depict the relationships in an easy to follow fashion.

**Comment by uryelah** [comment]
**@temesghentekeste This is the wrong project to raise this Issue as this is the scaffold repo, not the student repo.**

You should raise the issue at the forked branch, not the original microverse branch.

Please close this Issue, I apologize for the inconvenience. 🙂

**Comment by temesghentekeste** [comment]
Thanks @uryelah.
