### ISSUE TITLE
Peer to Peer Code Review 23 / 10 - Team 134

### ISSUE THREAD

**Issue by gurbuzertunga** [microverseinc/ror-social-scaffold#192]
Looks really good man. Congrats!

**Comment by uryelah** [comment]
**@gurbuzertunga This is the wrong project to raise this Issue as this is the scaffold repo, not the student repo.**

You should raise the issue at the forked branch, not the original microverse branch.

Please close this Issue, I apologize for the inconvenience. 🙂
