### ISSUE TITLE
Team-126-The-Kermits

### ISSUE THREAD

**Issue by Haywhizzz** [microverseinc/ror-social-scaffold#205]
- It's a great project

- Most of the features have been implemented and the project is ready for submission

**Comment by uryelah** [comment]
**@Haywhizzz This is the wrong project to raise this Issue as this is the scaffold repo, not the student repo.**

You should raise the issue at the forked branch, not the original Microverse branch.

--- 

If Issues are not currently habilitated in the forked repo you can habilitate them by:

- Going to the Settings page of your fork.

- Checking the box next to Issues.

---

I'm closing this Issue, I apologize for the inconvenience. 🙂
