### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by mricanho** [microverseinc/ror-social-scaffold#302]
Hello team!

You did an excellent job so far, just a few things to work on:

1. Try to refactor your update method in friends controller, you only need to use your existing friendId
2. Work on your views to accept or reject the friend request

Keep the good work! Happy coding!

**Comment by uryelah** [comment]
**@mricanho This is the wrong project to raise this Issue as this is the scaffold repo, not the student repo.**

You should raise the issue at the forked branch, not the original Microverse branch.

--- 

If Issues are not currently habilitated in the forked repo you can habilitate them by:

- Going to the Settings page of your fork.

- Checking the box next to Issues.

---

I'm closing this Issue, I apologize for the inconvenience. 🙂
