### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by gasb150** [microverseinc/ror-social-scaffold#339]
Good job with your project, but remember :

- [ ] Follow the steps as the documentation recommend, for the PostgreSQL database.
- [ ] Use the same ruby version in Gemfile and .rubyversion file.

- [ ] Trust in your stand-up team, the wants you complete Microverse and be successful in your career.

Enjoy your jornay. Happy coding 🔥  👩🏽‍💻  👍🏽

**Comment by SpaYco** [comment]
Hello there, this is the wrong place to post this issue, 
P.S: you can't make issues in a forked repo.
