### ISSUE TITLE
Test command in readme with spelling error.

### ISSUE THREAD

**Issue by mke2111** [microverseinc/ror-social-scaffold#381]
**In the readme file, specifically the test section, the test command has `rpsec` instead of `rspec`. This is obviously a spelling error.** 
Let's have this fixed. 😄  🥺

**Comment by euqueme** [comment]
Hi, @mke2111 great catch! :raised_hands: would you open a PR for it? :pray:

**Comment by mke2111** [comment]
I have created the PR with the readme update changes. @euqueme.
