### ISSUE TITLE
P2P code review

### ISSUE THREAD

**Issue by nyatindopatrick** [microverseinc/ror-social-scaffold#74]
Please leave some comments and suggestions.

**Comment by rammazzoti2000** [comment]
Great project @nyatindopatrick I like the the way you managed the current user to  avoid  self friendship request, quite simple but efficient, I still wasn't able to catch the bug on unfriend button, but otherwise all is great.

**Comment by patriciachrysy** [comment]
Good job on the v2 of friendship @nyatindopatrick, just that i saw two relationships in the Friendship model, the two are about friends and are has_many relationships. What i the aim of having those in Friendship model? Are they not supposed to be in the user model?

**Comment by dili021** [comment]
Nice looking code man! One thing I noticed in the friendships controller: you should put the redirect_to in both actions outside and after the if statement since it's the same in both conditons
``` 
   if @friend.save
     notice: 'friend request sent sucessfully!'
   else
     alert: 'Request failed!'
    end
  redirect_to users_path
end

**Comment by nyatindopatrick** [comment]
Thank you very much for the reviews.
