### ISSUE TITLE
Add linter and GHA config files and fix linter issues in SCSS files

### ISSUE THREAD

**Issue by euqueme** [microverseinc/ror-social-scaffold#75]
Hello peers, opening this issue because it will be easier to have these [linter files](https://github.com/microverseinc/linters-config/tree/master/ror) directly in this repo than having the students make this patch when rubocop does a styling check to SCSS files.

Thank you for in advance for all your feedback :pray:

**Comment by nidalaa** [comment]
@bolah2009 can you make sure we take care of it, please 🙏 ?

**Comment by bolah2009** [comment]
Sure @nidalaa, I was the one that asked @euqueme to open the issue.

Thanks, @euqueme for opening this. ❤️

**Comment by bolah2009** [comment]
To be clear again @euqueme, rubocop is not checking SCSS files, the [stylint](https://github.com/microverseinc/linters-config/blob/eaf15f3dacc4857aea68c0f988217a73b2e7fcd1/ror/.github/workflows/linters.yml#L36) is the one checking the SCSS files. This issue should be about adding workflow config as you suggested and fixing existing linter issues on the repo.
